# -*- coding: utf-8 -*-
"""Dữ liệu dịch: tên nhân vật, trợ thủ, bản đồ (Trung -> Việt)."""

FIGHTER_NAMES = {
    "ichigo": "Kurosaki Ichigo",
    "ichigo_bankai": "Kurosaki Ichigo Bankai",
    "ichigo_vizored_half": "Kurosaki Ichigo nửa Vizard",
    "ichigo_vizored": "Kurosaki Ichigo Vizard",
    "ichigo_zero": "Kurosaki Ichigo Zero",
    "ogihci": "Ichigo Hollow",
    "ogihci_bankai": "Ichigo Hollow Bankai",
    "rukia": "Kuchiki Rukia",
    "rukia_shikai": "Kuchiki Rukia Shikai",
    "renji": "Abarai Renji",
    "kenpachi": "Zaraki Kenpachi",
    "ikkaku": "Madarame Ikkaku",
    "gin": "Ichimaru Gin",
    "chad": "Sado Chad",
    "uryuu": "Ishida Uryuu",
    "toushirou": "Hitsugaya Toushirou",
    "toushirou_bankai": "Hitsugaya Toushirou Bankai",
    "byakuya": "Kuchiki Byakuya",
    "byakuya_bankai": "Kuchiki Byakuya Bankai",
    "ulquiorra": "Ulquiorra Cifer",
    "ulquiorra_resurreccion": "Ulquiorra Resurreccion",
    "aizen": "Aizen Sousuke",
    "mayuri": "Kurotsuchi Mayuri",
    "orihime": "Inoue Orihime",
    "grimmjow": "Grimmjow Jaegerjaquez",
    "soifon": "Soi Fon",
    "starrk": "Coyote Starrk",
    "naruto": "Uzumaki Naruto",
    "naruto_oneTail": "Uzumaki Naruto 1 Duôi",
    "naruto_fourTail": "Uzumaki Naruto 4 Duôi",
    "naruto_sennin": "Uzumaki Naruto Tiên Nhân",
    "naruto_kyubi": "Uzumaki Naruto Cửu Vĩ",
    "sakura": "Haruno Sakura",
    "sasuke": "Uchiha Sasuke",
    "sasuke_juin": "Uchiha Sasuke Dấu Nguyền",
    "sasuke_susanoo": "Uchiha Sasuke Susanoo",
    "karin": "Uzumaki Karin",
    "juggo": "Jugo",
    "itachi": "Uchiha Itachi",
    "deidara": "Deidara",
    "kakashi": "Hatake Kakashi",
    "kakashi_kamui": "Hatake Kakashi Kamui",
    "lee": "Rock Lee",
    "lee_tomon": "Rock Lee Cửa Đóng",
    "neji": "Hyuuga Neji",
    "gaara": "Gaara",
    "temari": "Temari",
    "jiraiya": "Jiraiya",
    "orochimaru": "Orochimaru",
    "killerbee": "Killer Bee",
    "pain": "Pain",
    "konan": "Konan",
    "obito": "Uchiha Obito",
    "obito_majime": "Uchiha Obito Nghiêm Túc",
    "madara": "Uchiha Madara",
    "kimimaro": "Kimimaro",
    "kenshin": "Himura Kenshin",
    "kenshin_battousai": "Himura Kenshin Battousai",
}

ASSIST_NAMES = {
    "kon": "Kon",
    "orihime": "Inoue Orihime",
    "yoruichi": "Shihouin Yoruichi",
    "uryuu": "Ishida Uryuu",
    "kenpachi": "Zaraki Kenpachi",
    "ogihci_vasteLord": "Ichigo Vasto Lorde",
    "yachiru": "Kusajishi Yachiru",
    "starrk": "Coyote Starrk",
    "halibel": "Tier Harribel",
    "grimmjow": "Grimmjow Jaegerjaquez",
    "soifon": "Soi Fon",
    "nemu": "Kurotsuchi Nemu",
    "ichigo_dangai": "Ichigo Dangai",
    "yamamoto": "Yamamoto Genryuusai",
    "gin": "Ichimaru Gin",
    "rangiku": "Matsumoto Rangiku",
    "byakuya": "Kuchiki Byakuya",
    "ikkaku": "Madarame Ikkaku",
    "gaara": "Gaara",
    "temari": "Temari",
    "ino": "Yamanaka Ino",
    "tenten": "Tenten",
    "itachi": "Uchiha Itachi",
    "hinata": "Hyuuga Hinata",
    "tsunate": "Tsunade",
    "tsuchikage": "Oonoki Tsuchikage",
    "minato": "Namikaze Minato",
    "jiraiya": "Jiraiya",
    "suigetsu": "Hoozuki Suigetsu",
    "sai": "Sai",
    "madara": "Uchiha Madara",
    "kimimaro": "Kimimaro",
    "shikamaru": "Nara Shikamaru",
    "obito_majime": "Uchiha Obito Nghiêm Túc",
    "sakura": "Haruno Sakura",
    "hiruko": "Sasori",
    "shishio": "Shishio Makoto",
}

MAP_NAMES = {
    "random": "Bản đồ ngẫu nhiên",
    "GenSe": "Giới Hiện",
    "Rukongai": "Phố Rukongai",
    "Seireitei": "Seireitei",
    "Sokyoku": "Đồi Sokyoku",
    "DanGai": "Khe Dangai",
    "ZangetsuHaka": "Mộ Zangetsu",
    "GoteiJusantai": "Gotei 13",
    "UchinaruSekai": "Thế Giới Nội Tâm",
    "KonohaMura": "Làng Lá Konoha",
    "HotSpring": "Suối Nước Nóng",
    "ShumatsuNoTani": "Thung Lũng Kết Thúc",
    "Roof": "Nóc Nhà",
    "UchihaMura": "Làng Uchiha",
    "Forest": "Rừng Rậm",
    "KirinoMura": "Làng Sương Mù",
}
