# -*- coding: utf-8 -*-
"""Dịch chuỗi UI trong ABC chính của FighterTester.swf (khớp CHÍNH XÁC toàn chuỗi).
KHÔNG dịch: các tên action/frame label (站�立, 走, 防御, 跳, 砍1, 摔1, 必杀, 万解, 击飞...)."""

ABC_TRANS = {
    "玩家 1": "Người chơi 1",
    "角色id": "ID nhân vật",
    "辅助id": "ID trợ thủ",
    "玩家 2": "Người chơi 2",
    "地图id": "ID bản đồ",
    "帧率": "FPS",
    "回血": "Hồi máu",
    "错误信息提示": "Thông báo lỗi",
    "开始测试": "Bắt đầu test",
    "显示判定": "Hiện hitbox",
    "秒杀 P2": "Xử lý P2",
    "Esc 键": "Phím Esc",
    "没有游戏数据！": "Không có dữ liệu game!",
    "正处于系统控制中！": "Hệ thống đang điều khiển!",
    "正处于暂停！": "Đang tạm dừng!",
    "当前为练习模式!": "Đang ở chế độ luyện tập!",
    "掉血：": "Mất máu: ",
    "秒杀 P2 成功！": "Đã xử lý P2 thành công!",
    "发送 ESC 按键事件完成!": "Đã gửi sự kiện phím ESC!",
    "关闭判定": "Tắt hitbox",
    "正在加载角色：": "Đang tải nhân vật: ",
    "正在加载辅助角色：": "Đang tải trợ thủ: ",
    "正在加载场景：": "Đang tải bản đồ: ",
    "正在加载BGM": "Đang tải nhạc nền",
    "返回到主菜单？": "Về menu chính?",
    "未定义必杀特写：": "Chưa định nghĩa cut-in đặc biệt: ",
    "小队模式": "Chơi đội",
    "闯关模式": "Đọc màn",
    "2P对战": "2 Người đấu",
    "对战电脑": "Đấu với máy",
    "观战电脑": "Xem máy đấu",
    "单人模式": "Chơi đơn",
    "游戏设置": "Cài đặt",
    "练习模式": "Luyện tập",
    "制作组": "Nhóm làm game",
    "更多游戏": "Game khác",
    "GameCtrl.addGameSprite :: team 为空！": "GameCtrl.addGameSprite :: team rỗng!",
    "关卡全部通过！": "Đã vượt qua tất cả các màn!",
    "下一关卡": "Màn kế tiếp",
    "前往继续场景": "Tiếp tục chơi",
    "返回选人菜单": "Về màn chọn người",
    "时间结束！": "Hết giờ!",
    "设置 ctrler 失败！": "Cài ctrler thất bại!",
    "冒险模式 - 小队": "Đọc màn - Đội",
    "玩家对战 - 小队": "Người đấu người - Đội",
    "电脑对战 - 小队": "Máy đấu máy - Đội",
    "观战模式 - 小队": "Xem máy đấu - Đội",
    "冒险模式 - 单人": "Đọc màn - Đơn",
    "玩家对战 - 单人": "Người đấu người - Đơn",
    "电脑对战 - 单人": "Máy đấu máy - Đơn",
    "观战模式 - 单人": "Xem máy đấu - Đơn",
    "未知模式": "Chế độ lạ",
    "读取角色数据失败！": "Lỗi tải dữ liệu nhân vật!",
    "读取辅助数据失败！": "Lỗi tải dữ liệu trợ thủ!",
    "读取选择场景数据失败！": "Lỗi tải dữ liệu màn chọn!",
    "读取地图数据失败！": "Lỗi tải dữ liệu bản đồ!",
    "读取关卡数据失败！": "Lỗi tải dữ liệu màn chơi!",
    "GameLogic.isInAir :: map 为空！": "GameLogic.isInAir :: map rỗng!",
    "GameLogic.isTouchBottomFloor :: map 为空！": "GameLogic.isTouchBottomFloor :: map rỗng!",
    "GameLogic.isOutRange :: map 为空！": "GameLogic.isOutRange :: map rỗng!",
    "开放BVN": "OpenBVN",
    "V3.x 开放BVN": "OpenBVN V3.x",
    "初始化资源完成！": "Tải tài nguyên xong!",
    "初始化游戏渲染": "Khởi tạo render",
    "初始化输入器": "Khởi tạo bộ nhập",
    "初始化游戏数据": "Khởi tạo dữ liệu game",
    "初始化配置": "Khởi tạo cấu hình",
    "初始化输入器配置": "Khởi tạo cấu hình phím",
    "初始化滚动域": "Khởi tạo vùng cuộn",
    "初始化场景控制器": "Khởi tạo bộ điều khiển màn",
    "初始化加载场景": "Khởi tạo màn tải",
    "帧率低：": "FPS thấp: ",
    "，帧数定位：": ", khung: ",
    "当前模式：": "Chế độ hiện tại: ",
    "游戏初始化：准备游戏资源": "Khởi tạo game: chuẩn bị tài nguyên",
    "游戏初始化：正在加载配置文件": "Khởi tạo game: đang tải file cấu hình",
    "游戏初始化失败：准备游戏资源失败：": "Lỗi khởi tạo: chuẩn bị tài nguyên thất bại: ",
    "游戏初始化失败：准备游戏资源失败!": "Lỗi khởi tạo: chuẩn bị tài nguyên thất bại!",
    "游戏初始化失败：加载配置文件失败：": "Lỗi khởi tạo: tải file cấu hình thất bại: ",
    "游戏初始化失败：加载配置文件失败!": "Lỗi khởi tạo: tải file cấu hình thất bại!",
    "游戏初始化：正在加载游戏资源": "Khởi tạo game: đang tải tài nguyên",
    " :: 进度超过 100%！": " :: tiến độ vượt 100%!",
    "游戏初始化：正在加载": "Khởi tạo game: đang tải ",
    "资源(": "tài nguyên(",
    "SoundCtrl.loadFightBGM :: 加载声音失败：": "SoundCtrl.loadFightBGM :: lỗi tải âm thanh: ",
    "初始化选择人物": "Khởi tạo chọn nhân vật",
    "初始化选择辅助": "Khởi tạo chọn trợ thủ",
    "SelectFighterStage.addFighterItem :: 没有找到角色数据：": "SelectFighterStage :: không thấy dữ liệu nhân vật: ",
    "重新选择？": "Chọn lại?",
    "选择地图": "Chọn bản đồ",
    "开始游戏！": "Bắt đầu!",
    "ID：": "ID: ",
    "NAME：": "TÊN: ",
    "未找到特殊帧：": "Không thấy frame đặc biệt: ",
    "该伤害为真实伤害，不可防御：": "Sát thương chuẩn, không đỡ được: ",
    "属性抗性：": "Kháng thuộc tính: ",
    "，减免伤害：": ", giảm sát thương: ",
    "物理吸血：": "Hút máu vật lý: ",
    "，吸取血量：": ", lượng hút: ",
    "关卡全部完成！": "Hoàn thành tất cả các màn!",
    "声音": "âm thanh",
    "特效": "hiệu ứng",
    "字体": "font chữ",
    "图片": "hình ảnh",
    "加载声音失败：": "Lỗi tải âm thanh: ",
    "加载失败：": "Lỗi tải: ",
    "字体图像加载失败：assets/font/font1.xml": "Lỗi tải ảnh font: assets/font/font1.xml",
    "字体 xml 加载失败：assets/font/font1.xml": "Lỗi tải xml font: assets/font/font1.xml",
    "GameLoader.loadFighter :: 角色 ID 不存在：": "GameLoader.loadFighter :: ID nhân vật không tồn tại: ",
    "角色 ID 错误！": "ID nhân vật sai!",
    "GameLoader.loadAssister :: 辅助 ID 不存在：": "GameLoader.loadAssister :: ID trợ thủ không tồn tại: ",
    "辅助 ID 错误！": "ID trợ thủ sai!",
    "GameLoader.loadMap :: 地图 ID 不存在：": "GameLoader.loadMap :: ID bản đồ không tồn tại: ",
    "地图 ID 错误！": "ID bản đồ sai!",
    "GameLoader.loadSWF :: 无法加载文件：": "GameLoader.loadSWF :: không tải được file: ",
    "加载 SWF 文件出错！": "Lỗi tải file SWF!",
    "GameLoader.loadSWF :: 加载文件：": "GameLoader.loadSWF :: đang tải file: ",
    "：未定义背景乐！": ": chưa định nghĩa nhạc nền!",
    "程序：剑jian<br/>人物：剑jian、数字化流天、L、V.临界幻想、Azrael、影、赤炎<br/>辅助：小海、主流<br/>图片：剑jian、数字化流天、社长星<br/>策划：剑jian、数字化流天<br/>贡献：灰原·银<br/><br/>优化：开放BVN<br/>版权：5DPLAY 版权所有，开放BVN 由 5DPLAY 技术支持":
        "Lập trình: Jianjian<br/>Nhân vật: Jianjian, Shuzihua Liutian, L, V.Linhgiới, Azrael, Anh, Chitiên<br/>Trợ thủ: Xiaohai, Zhuliu<br/>Hình ảnh: Jianjian, Shuzihua Liutian, Xake Tinh<br/>Thiết kế: Jianjian, Shuzihua Liutian<br/>Đóng góp: Haibara Gin<br/><br/>Tối ưu: OpenBVN<br/>Bản quyền: 5DPLAY, OpenBVN được hỗ trợ kỹ thuật bởi 5DPLAY",
    "上": "Lên",
    "下": "Xuống",
    "左": "Trái",
    "右": "Phải",
    "攻击": "Tấn công",
    "跳跃": "Nhảy",
    "冲刺": "Lướt",
    "技能": "Kỹ năng",
    "大招": "Đại kỹ",
    "特殊": "Đặc biệt",
    "] 不存在！": "] không tồn tại!",
    "是": "Có",
    "否": "Không",
    "FighterAttacker.fire :: hitModel 出错！": "FighterAttacker.fire :: lỗi hitModel!",
    "FighterAttacker.fire :: HitVO 出错！": "FighterAttacker.fire :: lỗi HitVO!",
    "FightUI.initlize :: 初始化分数": "FightUI.initlize :: khởi tạo điểm số",
    "设置全部": "Cài tất cả",
    "还原默认按键": "Khôi phục phím mặc định",
    "应用": "Áp dụng",
    "取消": "Hủy",
    "玩家1 按键设置": "Cài phím Người chơi 1",
    "玩家2 按键设置": "Cài phím Người chơi 2",
    "电脑等级": "Độ khó của máy",
    "非常简单": "Rất dễ",
    "简单": "Dễ",
    "正常": "Thường",
    "困难": "Khó",
    "非常困难": "Rất khó",
    "地狱": "Địa ngục",
    "按键操作模式": "Chế độ thao tác",
    "正常模式": "Kiểu thường",
    "经典模式": "Kiểu cổ điển",
    "生命值": "Máu",
    "对战时间": "Thời gian đấu",
    "30秒": "30 giây",
    "60秒": "60 giây",
    "90秒": "90 giây",
    "无限制": "Không giới hạn",
    "游戏音效": "Hiệu ứng âm thanh",
    "背景音乐": "Nhạc nền",
    "画质等级": "Chất lượng đồ họa",
    "低": "Thấp",
    "中": "Vừa",
    "高": "Cao",
    "最高": "Cao nhất",
    "知道了": "Đã hiểu",
    "BitmapAssetLoader.loadFail :: 加载失败：": "BitmapAssetLoader.loadFail :: lỗi tải: ",
    "BitmapAssetLoader.cacheBitmap 出错！": "BitmapAssetLoader.cacheBitmap lỗi!",
    "请按下一个键设置【": "Nhấn một phím để cài [",
    "】": "]",
    "返回标题": "Về màn hình chính",
    "返回": "Quay lại",
    "移除 AImain 完成！": "Đã gỡ AImain xong!",
    "出招表": "Bảng đòn",
    "返回选人": "Về chọn nhân vật",
    "继续游戏": "Chơi tiếp",
}

# Chữ trong màn "Cách chơi" (EditText tĩnh nhúng trong binary_3) — thay nội dung ban đầu
HOW2PLAY_TRANS = {
    "“左右按键”控制角色行走": '"Phím Trái/Phải" để di chuyển',
    "“下键”控制角色防御": '"Phím Xuống" để đỡ đòn',
    "普通攻击按键(可连打)": "Phím tấn công thường (bấm liên tiếp được)",
    "跳跃按键(可以在空中进行二次跳跃)": "Phím nhảy (có thể nhảy kép trên không)",
    "瞬步、冲刺步的按键": "Phím bước nhanh / lướt",
    "攻击按键2，基本技能键": "Phím tấn công 2, phím kỹ năng",
    "必杀的按键(需要一个能量)": "Phím kỹ năng đặc biệt (cần một năng lượng)",
    "招唤帮手的按键": "Phím triệu hồi trợ thủ",
    "请按下一个键设置【上】": "Nhấn một phím để cài [Lên]",
}

